services:
    db:
        image: mysql:latest
        container_name: todo_db
        restart: always
        env_file:
            - .env
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "33061:3306"
        healthcheck:
            test:
                [
                    "CMD",
                    "mysql",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-p${MYSQL_ROOT_PASSWORD}",
                    "-e",
                    "SELECT 1",
                ]
            timeout: 20s
            retries: 10
    backend:
        container_name: todo_backend
        build: ./todo_backend
        env_file:
            - .env
        command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./todo_backend:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PORT=${MYSQL_PORT}
    frontend:
        build: ./todo_frontend
        container_name: todo_frontend
        volumes:
            - ./todo_frontend:/app
        ports:
            - "3000:3000"
        depends_on:
            - backend

volumes:
    data:
